### ISSUE TITLE
redirect and  link 

### ISSUE THREAD

**Issue by nguyenquang2302** [PhuongNamCorpsIntern/workspace#2]
Có 2 vấn đề   cần giúp đỡ. hjx mọi người giúp với nhen! ( Fw sifoni)
- view 

```
form style="float:left" method="post" action="danh_muc"
                            input type="hidden" value="{{c.id}}" name="id"
                                button type="submit" class="gree"
```
- routing  có 
  '/danh_muc'=> 'admin\ProductcategoryController:getlist:listcategory::post',
  - controller có function
    public function listcategoryAction()
    {
    if($this->getPostData())
    {
    $postdata=$this->getPostData();
    $id=$postdata['id'];
    }
    }

2 vấn đề:
1.  bên 1 function khác mình muốn gọi
   return $this->redirect('listcategory')+ thêm truyền biến id qua để function listcategoryAction() có thể nhận được  id.  method="post" nha mọi người :)
   1. Có cách nào gọi tên (listcategory ) thay vì đường dẫn( danh_muc ) ngoài view ( twig)  không vậy mọi người.

thanks !

**Comment by khanhicetea** [comment]
`admin\ProductcategoryController:getlist:listcategory::post` mỗi tham số phân cách bằng dấu `:` nên ta có :
- `admin\ProductcategoryController` là controller
- `getlist` : method trong controller
- `listcategory` là name của _route_
- giá trị defaults ko có
- post : routing này chỉ thực hiện khi request = POST

để tạo ra đường dẫn tuyệt đối cho một route ta có các hàm sau :
- `$this->app->url($name_route)` : trong controller
- `{{ url(name_route) }}` trong twig , ví dụ là `{{ url('listcategory') }}`

khi muốn truyền tham số vào route thì thêm tham số $params là mảng vào, ví dụ :
- `$this->app->url($name_route, ['id' => 123])`
- `{{ url(name_route, {id: 123}) }}`

**Comment by nguyenquang2302** [comment]
ok tks anh :)

**Comment by nguyenquang2302** [comment]
khi em sử dụng :
`{{ url('listcategory', {id: 2}) }}`
hay 
`redirect($name_route, ['id' => 2])`
thì kết quả trả về vẫn là trên  phương thức get .dạng 
`danh_muc?id=2`
mà function em lấy là `getPostData('id')`
nên em vẫn k lấy được giá trị =_=

**Comment by khanhicetea** [comment]
sao ko dùng GET mà phải dùng POST thế ? mà dùng POST thì có thể thêm params vào route mà

**Comment by nguyenquang2302** [comment]
à em muốn ẩn cái id đi để người dùng không gõ bậy bạ  id trực tiếp vào đường dẫn đó anh.

**Comment by khanhicetea** [comment]
À, khi làm một rào cản hạn chế thì chú nên consider những thứ sau :
- người bình thường có mong muốn (rãnh) để làm điều đó không ?
- nếu đối với người có trình độ thì người ta có thể vượt qa rào cản ko ?

nếu câu trả lời là `No` AND `Yes` thì chú khôgn cần xây rào cản đâu :smile: 

còn nếu đã xây rào cản thì không cần giới hạn kiểu này đâu, cứ kiểm tra về quyền hạn, logic là ok

**Comment by nguyenquang2302** [comment]
ok anh em hiểu rồi a. thanks anh nhìu hehe
